// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sanaiy.DAL.Context;

#nullable disable

namespace sanaiy.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251201034620_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sanaiy.BLL.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CraftsmanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("IX_Addresses_ClientId");

                    b.HasIndex("CraftsmanId")
                        .IsUnique()
                        .HasDatabaseName("IX_Addresses_CraftsmanId")
                        .HasFilter("[CraftsmanId] IS NOT NULL");

                    b.HasIndex("ClientId", "IsDefault")
                        .HasDatabaseName("IX_Addresses_ClientId_IsDefault");

                    b.ToTable("Addresses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Address_Owner", "(ClientId IS NOT NULL AND CraftsmanId IS NULL) OR (ClientId IS NULL AND CraftsmanId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CraftsmanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PreferredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreferredTime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("PriceFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServicesName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("IX_Bookings_ClientId");

                    b.HasIndex("CraftsmanId")
                        .HasDatabaseName("IX_Bookings_CraftsmanId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Bookings_CreatedAt");

                    b.HasIndex("LocationId");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_Bookings_ServiceId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Bookings_Status");

                    b.HasIndex("ClientId", "Status")
                        .HasDatabaseName("IX_Bookings_ClientId_Status");

                    b.HasIndex("CraftsmanId", "Status")
                        .HasDatabaseName("IX_Bookings_CraftsmanId_Status");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Categories_IsActive");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Categories_Name");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PendingEmailConfirmation");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Clients_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Clients_IsActive");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Clients_Status");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Commission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ChargedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CraftsmanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("WalletTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("IX_Commissions_BookingId");

                    b.HasIndex("CraftsmanId")
                        .HasDatabaseName("IX_Commissions_CraftsmanId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Commissions_Status");

                    b.HasIndex("WalletTransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Commissions_WalletTransactionId")
                        .HasFilter("[WalletTransactionId] IS NOT NULL");

                    b.ToTable("Commissions", (string)null);
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Craftsman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CriminalRecordFile")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DrugTestFile")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IDCardImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("RatingAverage")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Applied");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Craftsmen_Category");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Craftsmen_Email");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("IX_Craftsmen_IsVerified");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Craftsmen_Status");

                    b.ToTable("Craftsmen", (string)null);
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("IX_PaymentTransactions_BookingId");

                    b.HasIndex("ClientId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_PaymentTransactions_Date");

                    b.HasIndex("ProviderReference")
                        .HasDatabaseName("IX_PaymentTransactions_ProviderReference");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PaymentTransactions_Status");

                    b.ToTable("PaymentTransactions", (string)null);
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CraftsmanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Sent");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("IX_Quotes_BookingId");

                    b.HasIndex("CraftsmanId")
                        .HasDatabaseName("IX_Quotes_CraftsmanId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Quotes_Status");

                    b.HasIndex("BookingId", "CraftsmanId")
                        .HasDatabaseName("IX_Quotes_BookingId_CraftsmanId");

                    b.ToTable("Quotes", (string)null);
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("CraftsmanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("IX_Reviews_BookingId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("IX_Reviews_ClientId");

                    b.HasIndex("CraftsmanId")
                        .HasDatabaseName("IX_Reviews_CraftsmanId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Reviews_CreatedAt");

                    b.HasIndex("Rating")
                        .HasDatabaseName("IX_Reviews_Rating");

                    b.ToTable("Reviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_Review_Rating", "Rating >= 1 AND Rating <= 5");
                        });
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPriceFixed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("OwnerCraftsmanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Services_CategoryId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Services_IsActive");

                    b.HasIndex("OwnerCraftsmanId")
                        .HasDatabaseName("IX_Services_OwnerCraftsmanId");

                    b.HasIndex("ServiceName", "OwnerCraftsmanId")
                        .HasDatabaseName("IX_Services_ServiceName_OwnerCraftsmanId");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Violation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CraftsmanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Submitted");

                    b.Property<Guid?>("TargetBookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CraftsmanId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Violations_CreatedAt");

                    b.HasIndex("ReporterUserId")
                        .HasDatabaseName("IX_Violations_ReporterUserId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Violations_Status");

                    b.HasIndex("TargetBookingId")
                        .HasDatabaseName("IX_Violations_TargetBookingId");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("IX_Violations_TargetUserId");

                    b.ToTable("Violations", (string)null);
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<Guid>("CraftsmanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFrozen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CraftsmanId")
                        .IsUnique();

                    b.ToTable("Wallets", (string)null);
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("RelatedBookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_WalletTransactions_CreatedAt");

                    b.HasIndex("RelatedBookingId")
                        .HasDatabaseName("IX_WalletTransactions_RelatedBookingId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_WalletTransactions_Type");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("IX_WalletTransactions_WalletId");

                    b.HasIndex("WalletId", "CreatedAt")
                        .HasDatabaseName("IX_WalletTransactions_WalletId_CreatedAt");

                    b.ToTable("WalletTransactions", (string)null);
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Address", b =>
                {
                    b.HasOne("sanaiy.BLL.Entities.Client", "Client")
                        .WithMany("Addresses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("sanaiy.BLL.Entities.Craftsman", "Craftsman")
                        .WithOne("Address")
                        .HasForeignKey("sanaiy.BLL.Entities.Address", "CraftsmanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Client");

                    b.Navigation("Craftsman");
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Booking", b =>
                {
                    b.HasOne("sanaiy.BLL.Entities.Client", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sanaiy.BLL.Entities.Craftsman", "Craftsman")
                        .WithMany("Bookings")
                        .HasForeignKey("CraftsmanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("sanaiy.BLL.Entities.Address", "Location")
                        .WithMany("Bookings")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("sanaiy.BLL.Entities.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Craftsman");

                    b.Navigation("Location");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Commission", b =>
                {
                    b.HasOne("sanaiy.BLL.Entities.Booking", "Booking")
                        .WithOne("Commission")
                        .HasForeignKey("sanaiy.BLL.Entities.Commission", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sanaiy.BLL.Entities.Craftsman", "Craftsman")
                        .WithMany("Commissions")
                        .HasForeignKey("CraftsmanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sanaiy.BLL.Entities.WalletTransaction", "WalletTransaction")
                        .WithOne("Commission")
                        .HasForeignKey("sanaiy.BLL.Entities.Commission", "WalletTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("Craftsman");

                    b.Navigation("WalletTransaction");
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("sanaiy.BLL.Entities.Booking", "Booking")
                        .WithOne("PaymentTransaction")
                        .HasForeignKey("sanaiy.BLL.Entities.PaymentTransaction", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sanaiy.BLL.Entities.Client", null)
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Quote", b =>
                {
                    b.HasOne("sanaiy.BLL.Entities.Booking", "Booking")
                        .WithMany("Quotes")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sanaiy.BLL.Entities.Craftsman", "Craftsman")
                        .WithMany("Quotes")
                        .HasForeignKey("CraftsmanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Craftsman");
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Review", b =>
                {
                    b.HasOne("sanaiy.BLL.Entities.Booking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("sanaiy.BLL.Entities.Review", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sanaiy.BLL.Entities.Client", "Client")
                        .WithMany("Reviews")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sanaiy.BLL.Entities.Craftsman", "Craftsman")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("CraftsmanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Client");

                    b.Navigation("Craftsman");
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Service", b =>
                {
                    b.HasOne("sanaiy.BLL.Entities.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sanaiy.BLL.Entities.Craftsman", "OwnerCraftsman")
                        .WithMany("Services")
                        .HasForeignKey("OwnerCraftsmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("OwnerCraftsman");
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Violation", b =>
                {
                    b.HasOne("sanaiy.BLL.Entities.Client", null)
                        .WithMany("ViolationsReported")
                        .HasForeignKey("ClientId");

                    b.HasOne("sanaiy.BLL.Entities.Craftsman", null)
                        .WithMany("ViolationsAgainst")
                        .HasForeignKey("CraftsmanId");

                    b.HasOne("sanaiy.BLL.Entities.Booking", "TargetBooking")
                        .WithMany("Violations")
                        .HasForeignKey("TargetBookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TargetBooking");
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Wallet", b =>
                {
                    b.HasOne("sanaiy.BLL.Entities.Craftsman", "Craftsman")
                        .WithOne("Wallet")
                        .HasForeignKey("sanaiy.BLL.Entities.Wallet", "CraftsmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Craftsman");
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.WalletTransaction", b =>
                {
                    b.HasOne("sanaiy.BLL.Entities.Booking", "RelatedBooking")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("RelatedBookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("sanaiy.BLL.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedBooking");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Address", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Booking", b =>
                {
                    b.Navigation("Commission");

                    b.Navigation("PaymentTransaction");

                    b.Navigation("Quotes");

                    b.Navigation("Review");

                    b.Navigation("Violations");

                    b.Navigation("WalletTransactions");
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Category", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Client", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Bookings");

                    b.Navigation("PaymentTransactions");

                    b.Navigation("Reviews");

                    b.Navigation("ViolationsReported");
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Craftsman", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Bookings");

                    b.Navigation("Commissions");

                    b.Navigation("Quotes");

                    b.Navigation("ReviewsReceived");

                    b.Navigation("Services");

                    b.Navigation("ViolationsAgainst");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Service", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("sanaiy.BLL.Entities.WalletTransaction", b =>
                {
                    b.Navigation("Commission");
                });
#pragma warning restore 612, 618
        }
    }
}
